language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: AMZXqInMwrrQZRIuBk8RAWGpAbqqUgCRDsjp1RaTHw23Pvv/Z0su+UuAZ9iuTnsgluW7M4k+ekOhR5D2PURpa+8nk/3JuCBt15MLgBKhXm5Oq3JS5MKW2x3up5me9FVC8teKPr7ExJeiyK8eat4sxNTR6pVke8CS1dVPHw772wNaT3CVEyFr8DQqIFub8ixg/MZgDayFrzQID4809XWWGcSkidKLzjuJA9eBGjgP2WHRRtbbhEplEmo/CAccuN0eLHFiSyNgqbzTFoGdEdopmDIwnkwB3t+MsuujVQbpdOqYvFoBPmROqJ74FJRU9TvCEX7w0iRBhjgHWjmlj9RxXE3t60DKA3LDOmsxpbVJRE3Vtj+nly3Hn7SK11feN7kUvPuwSH6/QxFijNISSuwn4ueZZYmYkmCsY9NX6YiRnRIU7uqfAFBXVq7NKD9rPdkfiZco1f1rCJMaRMkFhoizMu5wtYdKLsxRTHfLIwPAz2cvdBTtiJB6v/wKeNvDUFNWRYwxB0FxWYPjOEJVVHqrEB6O2uL0HC76s25tOO27GuRuIWpIQOdVmO0ZlmXUKC7Dalhx3EvI+Y722yrr5U7ILIesgDHYwjgHeaDJhPpI1cFhPPQepl3f4kvScpEj1DGlD3Yt7Iv4wR+I2hTFhxs+BI5wEdZpKXKrHfS432WGXTA=
  app: tranquil-everglades-28814
  on:
    repo: JacobAZimmerman/restaurants-app-mongoose
    branch: feature/with-tests
